# ------------------- wxmanager ------------------- #

kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: {{.Release.Name}}-wxmanager
  name: {{.Release.Name}}-wxmanager
spec:
  ports:
  - name: http
    port: {{.Values.wxmanager.service.http.port}}
    targetPort: {{.Values.wxmanager.service.http.targetPort}}
  selector:
    k8s-app: {{.Release.Name}}-wxmanager
  type: {{.Values.wxmanager.service.type}}
